### PR TITLE
let wget scripts use myproxy-logon if suitable Java unavailable

### PR DESCRIPTION
**Pull request by alaniwi**

### CODE REVIEW

**Comment by alaniwi** [comment]
Note that the script does not prompt for a password in the myproxy-logon case. The myproxy-logon command will do that itself.

**Comment by LucaCinquini** [comment]
Hi Alan,
	I assume you have doe extensive testing of this ? If so, I can merge it, but won’t time to test it.
thanks, Luca

**Comment by alaniwi** [comment]
Luca,

Here are the tests which I have done.  I tried on:

1) a machine with an appropriate version of java
2) a machine with no java but only myproxy-logon

and on each of these machines I have tried:

a) a CEDA openID
b) an openID from standard ESGF server (in fact, DKRZ)

For each of the four combinations, I removed the `~/.esg` directory and confirmed that it successfully obtained the certificate and then began downloading the data.

I also confirmed in each case that if I do not log in properly then the script aborts, and also that if I have an existing valid certificate (that is, if I do not remove the `~/.esg` directory) then it still proceeds to download skipping obtaining a certificate, as per existing behaviour.

I have also tested installing the modified template in the WEB-INF directory on a server, and confirmed that (after restarting the server), the new wget script which it generated matched the edited version of the previous script, which I had tested as described above before applying the diffs to the template. (It did match, apart from the generation timestamp of course.)

I also tested the effect on a machine with neither Java nor myproxy-logon installed.  In fact I don't have such a machine readily to hand, but I tested a copy of the script in which I introduced a deliberate typo inside `check_myproxy_logon()` so that it looked for the non-existent `myproxy-logonx` instead, and confirmed that the script then aborted with suitable error messages that neither java nor myproxy-logon could be found.

Please let me know if there are any other tests which you would like done.

Regards,
Alan

**Comment by LucaCinquini** [comment]
Sounds great, thanks for all of this, will merge.

**Pull request merged**
